## Build and run the Docker image ##

sudo: required

language: cpp

services:
  - docker

before_install:
# Update docker version from download.docker.com
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce

# Running and testing the build provided by the docker image
  #- docker build -t carlad/sinatra . # Will build using the Dockerfile in the github repo.
  - docker pull pontusla/compile_carpet
  #- sudo apt-get install valgrind -y
  - docker run --rm -ti --net=host pontusla/carpet_compile

# Only build the master and development branch.
branches:
  only:
  - master
  - development

# Notified via email if a build is broken or fixed.
notifications:
  email:
    - gusfransse@student.gu.se
    - gusgolko@student.gu.se
    - guslaepo@student.gu.se
    - elaineqvarnstrom@gmail.com
