#Maintainer: Sebastian Fransson , gusfransse@student.gu.se
version: '2' #Could be 3.
services:
    odsupercomponent:
        image: seresearch/2018-dit-168:v0.3.5-armhf
        network_mode: "host"
        restart: always
        volumes:
        - .:/opt/miniature.data
        command: "/opt/od4/bin/odsupercomponent --cid=111 --verbose=1 --configuration=/opt/miniature.data/configuration"

    proxy-miniature-pwm-motor:
        image: seresearch/2018-dit-168:v0.3.5-armhf
        depends_on:
        - odsupercomponent
        network_mode: "host"
        restart: always
        privileged: true
        volumes:
        - /sys/:/sys/
        - /dev/:/dev/
        command: "/opt/opendlv.miniature/bin/opendlv-proxy-miniature-pwm-motor --cid=111 --freq=50 --id=1"

    #Commander microservice.
    commander:
        image: microservice-commander:armhf
        depends_on:
        - proxy-miniature-pwm-motor #Requires the proxy container to be started before we can start.
        network_mode: "host"
        stdin_open: true # Makes it possible to receive inputs when attaching to the container.
        tty: true
        command: "/opt/microservice-commander.Service"
