FROM        debian
MAINTAINER  pontuslaestadius

# update and install dependencies
RUN         apt-get update \
                && apt-get install -y \
                    software-properties-common \
                    wget \
                && apt-get update \
                && apt-get install -y \
                    make \
                    git \
                    curl \
                    vim-gnome \
                && apt-get install -y cmake \
                && apt-get install -y #\
#                    gcc-7-base \
#                    gcc-7-arm-linux-gnueabihf-base \
#                    g++-4.9

#RUN sudo apt-get install gcc-arm-linux-gnueabihf
#RUN cmake .
#RUN make



